default["openclerk"]["database"] = "clerk"
default["openclerk"]["db_username"] = "clerk"
default["openclerk"]["path"] = "/var/www/openclerk"
default["openclerk"]["server_name"] = "localhost"
default["openclerk"]["server_remote_name"] = "localhost:80"
